import React from 'react';

// Images & Media

const MapBox = () => {
  return (
    <section className="mediaeye-layout-section withspace">
      <div className="mediaeye-layout-container">
        <div className="mediaeye-MapBox">
          <div className="mediaeye-MapBox-content">
            <div className="mediaeye-MapBox-content-head first">
              <h2>creators</h2>
            </div>
            <div className="mediaeye-MapBox-content-block">
              <p>Arlene</p>
              <p>Ronald</p>
              <p>Cody</p>
              <p>Kyle</p>
              <p>Darlene</p>
              <p>Esther</p>
              <p>Colleen</p>
              <p>Eduardo</p>
              <p>Courtney</p>
              <p>Mitchell</p>
              <p>Victoria</p>
              <p>Marjorie</p>
              <p>Cody</p>
              <p>Eduardo</p>
              <p>Shawn</p>
              <p>Aubrey</p>
              <p>Leslie</p>
              <p>Angel</p>
              <p>Ann</p>
              <p>Angel</p>
              <p>Arthur</p>
              <p>Philip</p>
              <p>Ronald</p>
              <p>Max</p>
              <p>Arlene</p>
              <p>Courtney</p>
              <p>Kristin</p>
              <p>Cameron</p>
              <p>Shane</p>
              <p>Victoria</p>
              <p>Arlene</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Shane</p>
              <p>Courtney</p>
              <p>Greg</p>
              <p>Marjorie</p>
              <p>Arlene</p>
              <p>Greg</p>
              <p>Darrell</p>
              <p>Cody</p>
              <p>Gladys</p>
              <p>Darlene</p>
              <p>Cameron</p>
              <p>Dianne</p>
              <p>Angel</p>
              <p>Marjorie</p>
              <p>Soham</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Debra</p>
              <p>Dianne</p>
              <p>Leslie</p>
              <p>Kristin</p>
              <p>Debra</p>
              <p>Kristin</p>
              <p>Shawn</p>
              <p>Arlene</p>
              <p>Angel</p>
            </div>
          </div>
          <div className="mediaeye-MapBox-content">
            <div className="mediaeye-MapBox-content-head sec">
              <h2>collections</h2>
            </div>
            <div className="mediaeye-MapBox-content-block">
              <p>Arlene</p>
              <p>Ronald</p>
              <p>Cody</p>
              <p>Kyle</p>
              <p>Darlene</p>
              <p>Esther</p>
              <p>Colleen</p>
              <p>Eduardo</p>
              <p>Courtney</p>
              <p>Mitchell</p>
              <p>Victoria</p>
              <p>Marjorie</p>
              <p>Cody</p>
              <p>Eduardo</p>
              <p>Shawn</p>
              <p>Aubrey</p>
              <p>Leslie</p>
              <p>Angel</p>
              <p>Ann</p>
              <p>Angel</p>
              <p>Arthur</p>
              <p>Philip</p>
              <p>Ronald</p>
              <p>Max</p>
              <p>Arlene</p>
              <p>Courtney</p>
              <p>Kristin</p>
              <p>Cameron</p>
              <p>Shane</p>
              <p>Victoria</p>
              <p>Arlene</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Shane</p>
              <p>Courtney</p>
              <p>Greg</p>
              <p>Marjorie</p>
              <p>Arlene</p>
              <p>Greg</p>
              <p>Darrell</p>
              <p>Cody</p>
              <p>Gladys</p>
              <p>Darlene</p>
              <p>Cameron</p>
              <p>Dianne</p>
              <p>Angel</p>
              <p>Marjorie</p>
              <p>Soham</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Debra</p>
              <p>Dianne</p>
              <p>Leslie</p>
              <p>Kristin</p>
              <p>Debra</p>
              <p>Kristin</p>
              <p>Shawn</p>
              <p>Arlene</p>
              <p>Angel</p>
            </div>
          </div>
          <div className="mediaeye-MapBox-content">
            <div className="mediaeye-MapBox-content-head third">
              <h2>Airdrops</h2>
            </div>
            <div className="mediaeye-MapBox-content-block ">
              <p>Arlene</p>
              <p>Ronald</p>
              <p>Cody</p>
              <p>Kyle</p>
              <p>Darlene</p>
              <p>Esther</p>
              <p>Colleen</p>
              <p>Eduardo</p>
              <p>Courtney</p>
              <p>Mitchell</p>
              <p>Victoria</p>
              <p>Marjorie</p>
              <p>Cody</p>
              <p>Eduardo</p>
              <p>Shawn</p>
              <p>Aubrey</p>
              <p>Leslie</p>
              <p>Angel</p>
              <p>Ann</p>
              <p>Angel</p>
              <p>Arthur</p>
              <p>Philip</p>
              <p>Ronald</p>
              <p>Max</p>
              <p>Arlene</p>
              <p>Courtney</p>
              <p>Kristin</p>
              <p>Cameron</p>
              <p>Shane</p>
              <p>Victoria</p>
              <p>Arlene</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Shane</p>
              <p>Courtney</p>
              <p>Greg</p>
              <p>Marjorie</p>
              <p>Arlene</p>
              <p>Greg</p>
              <p>Darrell</p>
              <p>Cody</p>
              <p>Gladys</p>
              <p>Darlene</p>
              <p>Cameron</p>
              <p>Dianne</p>
              <p>Angel</p>
              <p>Marjorie</p>
              <p>Soham</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Debra</p>
              <p>Dianne</p>
              <p>Leslie</p>
              <p>Kristin</p>
              <p>Debra</p>
              <p>Kristin</p>
              <p>Shawn</p>
              <p>Arlene</p>
              <p>Angel</p>
            </div>
          </div>
          <div className="mediaeye-MapBox-content">
            <div className="mediaeye-MapBox-content-head fourth">
              <h2>Events</h2>
            </div>
            <div className="mediaeye-MapBox-content-block ">
              <p>Arlene</p>
              <p>Ronald</p>
              <p>Cody</p>
              <p>Kyle</p>
              <p>Darlene</p>
              <p>Esther</p>
              <p>Colleen</p>
              <p>Eduardo</p>
              <p>Courtney</p>
              <p>Mitchell</p>
              <p>Victoria</p>
              <p>Marjorie</p>
              <p>Cody</p>
              <p>Eduardo</p>
              <p>Shawn</p>
              <p>Aubrey</p>
              <p>Leslie</p>
              <p>Angel</p>
              <p>Ann</p>
              <p>Angel</p>
              <p>Arthur</p>
              <p>Philip</p>
              <p>Ronald</p>
              <p>Max</p>
              <p>Arlene</p>
              <p>Courtney</p>
              <p>Kristin</p>
              <p>Cameron</p>
              <p>Shane</p>
              <p>Victoria</p>
              <p>Arlene</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Shane</p>
              <p>Courtney</p>
              <p>Greg</p>
              <p>Marjorie</p>
              <p>Arlene</p>
              <p>Greg</p>
              <p>Darrell</p>
              <p>Cody</p>
              <p>Gladys</p>
              <p>Darlene</p>
              <p>Cameron</p>
              <p>Dianne</p>
              <p>Angel</p>
              <p>Marjorie</p>
              <p>Soham</p>
              <p>Gladys</p>
              <p>Victoria</p>
              <p>Debra</p>
              <p>Dianne</p>
              <p>Leslie</p>
              <p>Kristin</p>
              <p>Debra</p>
              <p>Kristin</p>
              <p>Shawn</p>
              <p>Arlene</p>
              <p>Angel</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default MapBox;
